### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DCYN** [samhelmholtz/skinny-dip#1]
When I tried to follow the read me to reproduce the result in the paper I got below error. (EI Capitan, R 3.3.1) Would you please help to solve? Thanks.

runningExampleDataSet <- generateRunningExampleDataSet(); runningExampleDataMatrix <- as.matrix(runningExampleDataSet[,2:3]); resultLabels <- skinnyDipClusteringFullSpace(runningExampleDataMatrix); resultLabels[resultLabels==0] <- 8; plot(runningExampleDataMatrix[,1], runningExampleDataMatrix[,2], col=resultLabels);
Error in indexStart:indexEnd : argument of length 0

**Comment by samhelmholtz** [comment]
Hi! Thanks for your comment. There are a few commands in that code, which we put into one big long line in the readme. As a first step it would help to execute each command separately (i.e. separated by the ';' characters) to see where the error is occurring.

Otherwise, we didn't develop or test on a Mac unfortunately. Are you able to test on a Linux system for comparison? We're not able to reproduce this error on Ubuntu (15.04, R 3.3.1).

**Comment by DCYN** [comment]
Thanks. I tried in Ubuntu (16.04 R3.2.2). It still did not work. Would you please help? Thanks.

> resultLabels <- skinnyDipClusteringFullSpace(runningExampleDataMatrix);
> Error in getClustersInInterval(data, 1, length(data), "----", FALSE, debug,  : 
>   could not find function "dip.test"

**Comment by yejineun** [comment]
Hello, I am having the same issue with this package. If you could post a solution ASAP, that would be great! Thanks!

**Comment by samhelmholtz** [comment]
Hi @DCYN and @yejineun! Thanks for your comments. I understand that there are two different errors mentioned in this thread now. I'm going to assume that it's the second error you're both now stuck on (could not find function "dip test").

The error is of course saying that the dip.test function can't be found, which implies that our custom dip test package has not been installed and/or loaded. As mentioned in the readme.html file, please install our custom dip package with:

`library(devtools); install("$location$/code/skinny-dip/RPackageDipTestCustom/diptest");`

(where $location$ is the path to the directory you extracted this repository to).

Make sure that the package actually installs correctly. Installing this package requires compiling C++ code, which requires that you have a C++ compiler on your system (e.g. the "build-essential" package on Ubuntu). Make sure that the R console mentions that it was successfully installed. If there were any error or warning messages, investigate them to see if that might be causing the problem.

Once it's installed, you must load the library in order to use it. This is done with:

`library(diptest)`

Once that has been executed, you should be able to execute the command "?dip" to see the help docs for the dip, to verify that the package has been loaded correctly. Once you get to that point, our "running-example" code should work without problems.

**Comment by samhelmholtz** [comment]
I assume that my last comment addressed the problem. If required, feel free to open another issue.
